<!DOCTYPE html>
<html>
<head>
    <title>Laporan Keuangan</title>
    <style>
        body { font-family: sans-serif; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #333; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .text-right { text-align: right; }
        .green { color: green; }
        .red { color: red; }
        h2, p { text-align: center; margin: 0; }
    </style>
</head>
<body>
    <h2>Laporan Keuangan Pribadi</h2>
    <p>Generated by MyFinance App Gusti Swandana</p>
    <p>Tanggal Cetak: {{ date('d M Y') }}</p>
    <hr>

    <h3>Rekapitulasi Bulanan</h3>
    <table>
        <thead>
            <tr>
                <th>Bulan</th>
                <th class="text-right">Pemasukan</th>
                <th class="text-right">Pengeluaran</th>
                <th class="text-right">Bersih (Net)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($monthlyStats as $stat)
            @php
                $net = $stat->total_income - $stat->total_expense;
                $monthName = \Carbon\Carbon::createFromFormat('Y-m', $stat->month)->format('F Y');
            @endphp
            <tr>
                <td>{{ $monthName }}</td>
                <td class="text-right green">Rp {{ number_format($stat->total_income, 0, ',', '.') }}</td>
                <td class="text-right red">Rp {{ number_format($stat->total_expense, 0, ',', '.') }}</td>
                <td class="text-right" style="font-weight: bold;">
                    Rp {{ number_format($net, 0, ',', '.') }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>